try{
  ...
} catch {
  case e: IOException
} finally {

}
